dist: focal
arch:
  - amd64


language: python
python:
    - 3.9-dev



before_install:
    - sudo apt-get install -y graphviz python3-sklearn python3-pandas python3-sqlalchemy python3-matplotlib jupyter-notebook python3-ipython python3-scipy python3-numpy python3-dill python3-pydot


cache:
directories:
- $HOME/.cache/matplotlib

install: 
    pip install numpy scipy pandas sklearn matplotlib pydot dill sqlalchemy jupyter xgboost ipython lightgbm


script: 
    - export PYTHONPATH=$PYTHONPATH:..
    - df
    - free
    - cat /proc/cpuinfo
    - mkdir -p logs
    - rm -rf ~/.matplotlib
    - rm -rf ~/.cache/matplotlib
    - rm -rf ~/.matplotlib/fontList.cache  
    - fc-cache 
    - python ./tests/bugs/issue_36/display_version_info.py
    - python tests/demos/demo1.py
    - python tests/func/test_ozone.py
    - python tests/func/test_air_passengers.py
    - make PYTHON=python -f tests/Makefile build-test
    - python scripts/upload_to_chunk.io.py
    - pip install .
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute docs/sample_code.ipynb
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute docs/PyAF_Introduction.ipynb
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute docs/PyAF_Exogenous.ipynb
    
